//! Compiles the vendored cmark-gfm C sources.
//!
//! The submodule at `vendor/swift-cmark` is pinned to the SAME revision the Mac
//! app resolves through SwiftPM (see `Package.resolved`). Compiling that exact
//! source rather than linking a distro `libcmark-gfm` is what makes the two
//! platforms emit byte-identical HTML *by construction* instead of by luck —
//! `data-sourcepos` is the anchor the editor/preview sync maps through, so a
//! parser that is merely close is worse than one that is obviously wrong.
//!
//! `tests/vendor_pin.rs` asserts the submodule and `Package.resolved` agree.
//!
//! It also generates `web_assets.rs`, which compiles the shared web layer into
//! the binary — see `generate_web_assets`.
//!
//! Upstream builds these sources with CMake, but swift-cmark checks in the
//! headers CMake would otherwise generate (`cmark-gfm_config.h`,
//! `cmark-gfm_version.h`, `export.h`) so SwiftPM can build them directly. That
//! means `cc` can too — no CMake, and no system cmark-gfm package.

use std::path::{Path, PathBuf};

/// Sources excluded from both directories: re2c inputs, not C.
const EXCLUDED: &[&str] = &["scanners.re", "ext_scanners.re"];

fn main() {
    generate_web_assets();

    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("vendor/swift-cmark");

    let sentinel = root.join("src/include/cmark-gfm.h");
    if !sentinel.exists() {
        panic!(
            "vendored cmark-gfm sources missing at {}\n\
             run: git submodule update --init --recursive",
            root.display()
        );
    }

    let mut build = cc::Build::new();
    build
        .include(root.join("src/include"))
        .include(root.join("extensions/include"))
        .warnings(false);

    for dir in ["src", "extensions"] {
        for file in c_sources(&root.join(dir)) {
            build.file(file);
        }
    }

    build.compile("cmark-gfm");

    println!("cargo:rerun-if-changed={}", root.join("src").display());
    println!("cargo:rerun-if-changed={}", root.join("extensions").display());
}

/// Every `.c` file in `dir`, sorted so the compile is reproducible, minus the
/// re2c inputs.
fn c_sources(dir: &Path) -> Vec<PathBuf> {
    let mut files: Vec<PathBuf> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .map(|entry| entry.expect("dir entry").path())
        .filter(|p| p.extension().and_then(|e| e.to_str()) == Some("c"))
        .filter(|p| !EXCLUDED.iter().any(|name| p.ends_with(name)))
        .collect();
    files.sort();
    files
}

// --- the shared web layer, compiled in --------------------------------------

/// Files that are build tooling rather than served assets.
const NOT_SERVED: &[&str] = &["vendor.fish", "vendor.json"];

/// Write `web_assets.rs`: every file of the shared web layer as a
/// `(relative path, bytes)` pair, sorted by path.
///
/// Sorted because `assets.rs` binary-searches the table, and because an
/// unsorted `read_dir` order would make the generated file — and so the
/// binary — differ between builds of identical input.
///
/// The bytes go in through `include_bytes!` rather than being written into the
/// generated source: escaping 6 MB of font and JavaScript into Rust literals
/// would be slower to compile, unreadable, and pointless when the linker can
/// take the files as they are.
fn generate_web_assets() {
    let repo = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..");
    // `web/` after the Task 1 promotion, the SwiftPM resource directory before
    // it — the same precedence as `resources.rs` and `build/linux.fish`.
    let web = ["web", "Sources/TVMVCore/Resources/web"]
        .iter()
        .map(|c| repo.join(c))
        .find(|p| p.join("boot.js").is_file())
        .unwrap_or_else(|| {
            panic!(
                "shared web layer not found under {} — looked for web/ and \
                 Sources/TVMVCore/Resources/web/",
                repo.display()
            )
        });

    let mut files = Vec::new();
    collect(&web, &web, &mut files);
    files.sort();
    assert!(
        files.iter().any(|(key, _)| key == "boot.js"),
        "the web layer is there but boot.js is not in the collected set"
    );

    let mut out = String::from(
        "// @generated by build.rs from the shared web layer. Do not edit.\n\
         pub static ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for (key, path) in &files {
        // Paths are repo paths on this machine; no escaping subtlety beyond
        // the quoting, and a path containing a quote would fail to compile
        // rather than do anything interesting.
        out.push_str(&format!("    ({key:?}, include_bytes!({:?})),\n", path.display().to_string()));
        println!("cargo:rerun-if-changed={}", path.display());
    }
    out.push_str("];\n");

    let dest = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR")).join("web_assets.rs");
    std::fs::write(&dest, out).unwrap_or_else(|e| panic!("writing {}: {e}", dest.display()));

    // Additions and removals change the directory listing, not any one file.
    println!("cargo:rerun-if-changed={}", web.display());
    for dir in walk_dirs(&web) {
        println!("cargo:rerun-if-changed={}", dir.display());
    }
}

/// Every served file under `dir`, as `(path relative to `base`, absolute path)`.
fn collect(base: &Path, dir: &Path, out: &mut Vec<(String, PathBuf)>) {
    let entries = std::fs::read_dir(dir).unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()));
    for entry in entries {
        let path = entry.expect("dir entry").path();
        let name = path.file_name().and_then(|n| n.to_str()).unwrap_or_default().to_string();
        if name.starts_with('.') {
            continue;
        }
        if path.is_dir() {
            collect(base, &path, out);
            continue;
        }
        if NOT_SERVED.contains(&name.as_str()) {
            continue;
        }
        let key = path
            .strip_prefix(base)
            .expect("collected under base")
            .to_str()
            .unwrap_or_else(|| panic!("non-UTF-8 asset path: {}", path.display()))
            .to_string();
        out.push((key, path));
    }
}

fn walk_dirs(dir: &Path) -> Vec<PathBuf> {
    let mut found = Vec::new();
    if let Ok(entries) = std::fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                found.push(path.clone());
                found.extend(walk_dirs(&path));
            }
        }
    }
    found
}
